spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:5432}/${AUTH_DB_NAME:auth-db}
spring.datasource.username=${AUTH_DB_USER:dudu}
spring.datasource.password=${AUTH_DB_PASSWORD:ubnt2020}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

api.issuer.jwt=${AUTH_SERVICE_ISSUER:secret}
api.secret.key.jwt=${AUTH_SERVICE_SECRET:issuer}