spring.application.name=auth-service
spring.profiles.active=dev

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
spring.datasource.username=${AUTH_DB_USER}
spring.datasource.password=${AUTH_DB_PASSWORD}

api.issuer.jwt=${AUTH_SERVICE_ISSUER}
api.secret.key.jwt=${AUTH_SERVICE_SECRET}