networks:
  auth-service-nt:
    driver: bridge

services:
  auth-service-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=${AUTH_DB_AUTH_METHOD}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - auth-db:/var/lib/postgresql/data
    networks:
      - auth-service-nt

volumes:
  auth-db: